apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: hello-world
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
deploy:
  kubectl:
    manifests:
      - ./k8s/deployment.yaml
