apiVersion: skaffold/v2beta28
kind: Config
build:
  artifacts:
  - image: hello-world
    context: app
    sync:
      manual:
      - src: 'src/components/*'
        dest: .
      - src: 'src/styles/*'
        dest: .
deploy:
  kustomize:
    paths:
    - k8s/dev
profiles:
 - name: dev
   deploy:
     kustomize:
       paths:
       - k8s/dev
 - name: prod
   deploy:
     kustomize:
       paths:
       - k8s/prod
    
